SELECT CI.CITY,CO.COUNTRY 
FROM CITY CI 
LEFT JOIN COUNTRY CO ON CI.COUNTRY_ID = CO.COUNTRY_ID; -- 1.SORU


SELECT PA.PAYMENT_ID,CUST.FIRST_NAME,CUST.LAST_NAME 
FROM CUSTOMER CUST 
LEFT JOIN PAYMENT PA ON CUST.CUSTOMER_ID = PA.CUSTOMER_ID; -- 2.SORU


SELECT RE.RENTAL_ID,CUST.FIRST_NAME,CUST.LAST_NAME
FROM CUSTOMER CUST
LEFT JOIN RENTAL RE ON CUST.CUSTOMER_ID = RE.CUSTOMER_ID; --3.SORU


