SELECT C.CITY,CO.COUNTRY 
FROM CITY C
INNER JOIN COUNTRY CO ON CO.COUNTRY_ID = C.COUNTRY_ID; --1.SORU



SELECT PA.PAYMENT_ID,CUST.FIRST_NAME,CUST.LAST_NAME
FROM PAYMENT PA
INNER JOIN CUSTOMER CUST ON CUST.CUSTOMER_ID = PA.CUSTOMER_ID; --2.SORU


SELECT RE.RENTAL_ID,CUST.FIRST_NAME,CUST.LAST_NAME
FROM RENTAL RE
INNER JOIN CUSTOMER CUST ON CUST.CUSTOMER_ID = RE.CUSTOMER_ID;